version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:$PORT debtcore.wsgi:application
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - DEBUG=1
      - PORT=8000
      - PYTHONPATH=/app/debtcore:$PYTHONPATH
      - DJANGO_SETTINGS_MODULE=debtcore.settings

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      backend:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      - DEBUG=1
      - PYTHONPATH=/app/debtcore:$PYTHONPATH
      - DJANGO_SETTINGS_MODULE=debtcore.settings
    command: celery -A debtcore.celery worker -l info
    ports:
      - 6000:6000

  celerybeat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      backend:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      - DEBUG=1
      - PYTHONPATH=/app/debtcore:$PYTHONPATH
      - DJANGO_SETTINGS_MODULE=debtcore.settings
    command: celery -A debtcore.celery beat -l info

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_DATABASE: 'debtcore'
      MYSQL_USER: 'lucid'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build: 
      context: ./debtcore/vue-app
      dockerfile: Dockerfile
    command: sh -c "npm run dev"
    ports:
      - "5174:5174"
    volumes:
      - ./debtcore/vue-app:/app
      - /app/node_modules
    environment:
      - BROWSER=none
      - VITE_BACKEND_URL='https://3c0f-211-26-122-216.ngrok-free.app'
    env_file:
      - .env
    depends_on:
      backend:
        condition: service_started

volumes:
  dbdata:
  rabbitmq_data:
