version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:latest
    command: sh -c "sleep 10 && python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 --wait-for-client manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
      - "5678:5678"  
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/debtcore:$PYTHONPATH
      - PORT=8000

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      backend:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    env_file:
      - .env
    command: python -m debugpy --listen 0.0.0.0:6000 --wait-for-client -m celery -A debtcore.celery worker -l info
    ports:
      - 6000:6000

  celerybeat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      backend:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    env_file:
      - .env
    command: celery -A debtcore.celery beat -l info

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_DATABASE: 'debtcore'
      MYSQL_USER: 'lucid'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  dbdata:
  rabbitmq_data:
