# Generated by Django 5.0.3 on 2024-04-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debtbacklog',
            old_name='debt_backlog',
            new_name='debt',
        ),
    ]
