# Generated by Django 5.0.3 on 2024-04-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_address_country_company_email_company_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_registration_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
