# Generated by Django 5.0.3 on 2024-04-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_debt_backlog_debtbacklog_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtbacklog',
            name='is_system_generated',
            field=models.BooleanField(default=False),
        ),
    ]
