# Generated by Django 5.0.3 on 2024-04-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_surname_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'System Admin'), (2, 'Company Admin'), (3, 'Company Staff')], default='companystaff', max_length=12),
        ),
    ]
