# Generated by Django 5.0.3 on 2024-04-04 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_company_users_user_company'),
    ]

    operations = [
    ]
