# Generated by Django 5.0.3 on 2024-04-10 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customer_company_alter_user_role_debt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_address', to='app.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='postcode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(max_length=255, null=True, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='company',
            name='streetAddress',
            field=models.CharField(max_length=255, null=True, verbose_name='Street Address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_country', to='app.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='postcode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(max_length=255, null=True, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='customer',
            name='streetAddress',
            field=models.CharField(max_length=255, null=True, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_customer', to='app.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_user', to='app.company'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
