# Generated by Django 5.0.3 on 2024-04-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_address_city_remove_address_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='business_registration_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
