# Generated by Django 5.0.3 on 2024-04-04 01:16

from django.db import migrations

def assign_default_company(apps, schema_editor):
    User = apps.get_model('app', 'User')
    Company = apps.get_model('app', 'Company')
    default_company = Company.objects.first()
    if not default_company:
        default_company = Company.objects.create(name='Default Company')
    User.objects.filter(company__isnull=True).update(company=default_company)

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_user_company'),
    ]

    operations = [
        migrations.RunPython(assign_default_company),
    ]
