# Generated by Django 5.0.3 on 2024-04-10 06:39

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_customer_business_registration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='document',
            field=models.ImageField(default=1, upload_to=app.validators.debt_document_path, validators=[app.validators.validate_file_extension]),
            preserve_default=False,
        ),
    ]
