# Generated by Django 5.0.3 on 2024-04-04 02:52

from django.db import migrations, models


def assign_admin_role(apps, schema_editor):
    User = apps.get_model('app', 'User')
    first_user = User.objects.order_by('id').first() 
    if first_user:
        first_user.role = 'systemadmin'
        first_user.save()
    
class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20240404_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('systemadmin', 'System Admin'), ('companyadmin', 'Company Admin'), ('companystaff', 'Company Staff')], default='companystaff', max_length=12),
        ),
        migrations.RunPython(assign_admin_role),

    ]
