# Generated by Django 5.0.3 on 2024-04-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_company_created_by_company_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='whatsapp_business_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
