# Generated by Django 5.0.3 on 2024-04-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='meta_access_token',
            field=models.CharField(blank=True, help_text='Meta access token', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='meta_token_created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
