# Generated by Django 5.0.3 on 2024-04-24 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappuser',
            name='whatsapp_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_company_phone', to='app.whatsappphonenumber'),
        ),
    ]
