# Generated by Django 5.0.3 on 2024-04-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_company_meta_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='meta_is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='meta_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
