# Generated by Django 5.0.3 on 2024-04-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_whatsappuser_whatsapp_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappuser',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
