# Generated by Django 5.0.3 on 2024-05-02 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_company_meta_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_company', to='app.company'),
        ),
        migrations.AlterField(
            model_name='session',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
