# Generated by Django 5.0.3 on 2024-04-21 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_company_meta_is_valid_company_meta_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='whatsapp_phone_number_id',
        ),
        migrations.CreateModel(
            name='WhatsAppPhoneNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('verified_name', models.CharField(max_length=255)),
                ('display_phone_number', models.CharField(max_length=20)),
                ('quality_rating', models.CharField(max_length=50)),
                ('platform_type', models.CharField(max_length=100)),
                ('last_onboarded_time', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_phone_numbers', to='app.company')),
            ],
        ),
    ]
