# Generated by Django 5.0.3 on 2024-04-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_whatsappuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappuser',
            name='whatsapp_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
