# Generated by Django 5.0.3 on 2024-05-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_session_company_alter_session_complete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='payload',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
