# Generated by Django 5.0.3 on 2024-04-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_whatsappphonenumber_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappphonenumber',
            name='is_default_phone',
            field=models.BooleanField(default=False),
        ),
    ]
