# Generated by Django 5.0.3 on 2024-05-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_session_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status_code',
            field=models.IntegerField(default=0),
        ),
    ]
