# Generated by Django 5.0.3 on 2024-05-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_session_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
