# Generated by Django 5.0.3 on 2024-04-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_whatsappphonenumber_is_default_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappphonenumber',
            name='phone_number_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
