# Generated by Django 5.0.3 on 2024-05-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_session_whatsapp_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappphonenumber',
            name='display_phone_number',
        ),
        migrations.RemoveField(
            model_name='whatsappphonenumber',
            name='phone_number_id',
        ),
        migrations.RemoveField(
            model_name='whatsappphonenumber',
            name='verified_name',
        ),
        migrations.AddField(
            model_name='whatsappuser',
            name='display_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
