# Generated by Django 5.0.3 on 2024-04-23 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_whatsappphonenumber_phone_number_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappphonenumber',
            name='about',
            field=models.CharField(blank=True, max_length=139, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='whatsappphonenumber',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='whatsappphonenumber',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='whatsappphonenumber',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='whatsappphonenumber',
            name='vertical',
            field=models.CharField(blank=True, choices=[(1, 'UNDEFINED'), (2, 'OTHER'), (3, 'AUTO'), (4, 'BEAUTY'), (5, 'APPAREL'), (6, 'EDU'), (7, 'ENTERTAIN'), (8, 'EVENT_PLAN'), (9, 'FINANCE'), (10, 'GROCERY'), (11, 'GOVT'), (12, 'HOTEL'), (13, 'HEALTH'), (14, 'NONPROFIT'), (15, 'PROF_SERVICES'), (16, 'RETAIL'), (17, 'TRAVEL'), (18, 'RESTAURANT'), (19, 'NOT_A_BIZ')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='whatsappphonenumber',
            name='website1',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='whatsappphonenumber',
            name='website2',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppUser',
            fields=[
                ('whatsapp_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('message_type', models.CharField(choices=[('1', 'Text'), ('2', 'Image'), ('3', 'Video'), ('4', 'Audio'), ('5', 'Document')], max_length=10)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.company')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.conversation')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='app.whatsappuser')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='app.whatsappuser')),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations_participants', to='app.whatsappuser'),
        ),
    ]
