# Generated by Django 5.0.3 on 2024-04-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_whatsappphonenumber_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappphonenumber',
            name='vertical',
            field=models.CharField(blank=True, choices=[('UNDEFINED', 'Undefined'), ('OTHER', 'Other'), ('AUTO', 'Auto'), ('BEAUTY', 'Beauty'), ('APPAREL', 'Apparel'), ('EDU', 'Education'), ('ENTERTAIN', 'Entertainment'), ('EVENT_PLAN', 'Event Planning'), ('FINANCE', 'Finance'), ('GROCERY', 'Grocery'), ('GOVT', 'Government'), ('HOTEL', 'Hotel'), ('HEALTH', 'Health'), ('NONPROFIT', 'Nonprofit'), ('PROF_SERVICES', 'Professional Services'), ('RETAIL', 'Retail'), ('TRAVEL', 'Travel'), ('RESTAURANT', 'Restaurant'), ('NOT_A_BIZ', 'Not a Business')], max_length=14, null=True),
        ),
    ]
