# Generated by Django 5.0.3 on 2024-05-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_whatsappphonenumber_display_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhatsAppPhoneNumber',
            new_name='WhatsAppCompanyProfile',
        ),
        migrations.RenameField(
            model_name='whatsappuser',
            old_name='whatsapp_phone',
            new_name='whatsapp_company_profile',
        ),
        migrations.RemoveField(
            model_name='whatsappuser',
            name='display_phone_number',
        ),
    ]
