# Generated by Django 5.0.3 on 2024-04-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_whatsappphonenumber_vertical'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappphonenumber',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
