# Generated by Django 5.0.3 on 2024-05-04 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_whatsappphonenumber_whatsappcompanyprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappuser',
            name='company',
        ),
        migrations.RemoveField(
            model_name='whatsappuser',
            name='whatsapp_company_profile',
        ),
        migrations.AddField(
            model_name='whatsappuser',
            name='company_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_users', to='app.whatsappcompanyprofile'),
        ),
    ]
