# Generated by Django 5.0.3 on 2024-05-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_whatsappuser_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcompanyprofile',
            name='whatsapp_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
