# Generated by Django 5.0.3 on 2024-05-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_whatsappcompanyprofile_whatsapp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappcompanyprofile',
            name='about',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappcompanyprofile',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappcompanyprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
    ]
