# Generated by Django 5.0.3 on 2024-05-04 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_whatsappuser_company_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappcompanyprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_phone_numbers_company', to='app.company'),
        ),
    ]
