# Generated by Django 5.0.3 on 2024-05-04 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_whatsappcompanyprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_user_company', to='app.company'),
        ),
    ]
