# Generated by Django 5.0.3 on 2024-05-04 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_whatsappuser_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_users_company', to='app.company'),
        ),
        migrations.AlterField(
            model_name='whatsappuser',
            name='company_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_profile_company', to='app.whatsappcompanyprofile'),
        ),
    ]
