# Generated by Django 5.0.3 on 2024-05-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_whatsappuser_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='footer',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='header',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='message_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='message_type',
            field=models.CharField(choices=[('1', 'Text'), ('2', 'Image'), ('3', 'Video'), ('4', 'Audio'), ('5', 'Document'), ('6', 'Template')], max_length=10),
        ),
    ]
