# Generated by Django 5.0.3 on 2024-05-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_due_date_debt_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='term',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
