# Generated by Django 5.0.3 on 2024-05-08 05:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_debt_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='session',
            name='payload',
        ),
        migrations.AddField(
            model_name='session',
            name='additional_info',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='session',
            name='debt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_debt', to='app.debt'),
        ),
        migrations.AddField(
            model_name='session',
            name='invoice',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
