# Generated by Django 5.0.3 on 2024-05-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_session_event_type_remove_session_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='event_type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
