# Generated by Django 5.0.3 on 2024-05-08 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_session_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='complete_date',
            new_name='completed_date',
        ),
        migrations.AddField(
            model_name='session',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='webhook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_webhook', to='app.webhook'),
        ),
    ]
