# Generated by Django 5.0.3 on 2024-05-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_session_change_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
