# Generated by Django 5.0.3 on 2024-05-13 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_session_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 13, 4, 28, 35, 569498, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
