# Generated by Django 5.0.3 on 2024-05-17 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_country_phone_code_alter_debt_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
