# Generated by Django 5.0.3 on 2024-05-18 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_debt_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'verbose_name_plural': 'Debts'},
        ),
    ]
