# Generated by Django 5.0.3 on 2024-06-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_debt_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='status',
            field=models.CharField(choices=[(1, 'In Progress'), (2, 'Claimed'), (3, 'Canceled')], default='1', max_length=12),
        ),
    ]
