# Generated by Django 5.0.3 on 2024-06-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_company_bukku_access_token_company_bukku_api_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bukku_last_sync_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
