# Generated by Django 5.0.3 on 2024-06-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_debt_bukku_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='bukku_is_voided',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
