from enum import Enum

class HookType(Enum):
  META_WHATSAPP = 1
  
class HookStatus(Enum):
  QUEUED = 0
  PROCESSED = 1
  SKIPPED = 2
  FAILED = 3
  
class TransactionStatus(Enum):
  QUEUED = 0
  COMPLETED = 1
  FAILED = 2
  COMPLETED_SKIPPED = 3
  COMPLETED_WITH_WARNING = 4
  FAILED_MAPPING = 5
  
class StatusCode(Enum):
  WAITING_TO_BE_PROCESSED = 0
  COMPANY_DISABLED = 1
  
  # Whatsapp Message (100-199)
  WHATSAPP_MESSAGE_SUCESS = 100
  WHATSAPP_MESSAGE_FAILED = 101
  WHATSAPP_MESSAGE_MISSING_SENDER_PHONE_NUMBER = 110
  WHATSAPP_MESSAGE_SENDER_NOT_FOUND = 111
  
class EventType(Enum):
  INVALID = 0
  WHATSAPP_MESSAGE = 10
  