from enum import Enum

class HookType(Enum):
  META_WHATSAPP = 1
  
class HookStatus(Enum):
  QUEUED = 0
  PROCESSED = 1
  SKIPPED = 2
  FAILED = 3
  
class TransactionStatus(Enum):
  QUEUED = 0
  COMPLETED = 1
  FAILED = 2
  COMPLETED_SKIPPED = 3
  COMPLETED_WITH_WARNING = 4
  FAILED_MAPPING = 5
  
class StatusCode(Enum):
  WAITING = 0
  COMPANY_DISABLED = 1
  
  # Whatsapp Message (100-199)
  WHATSAPP_MESSAGE_SUCCESS = 100
  WHATSAPP_MESSAGE_FAILED = 101
  WHATSAPP_MESSAGE_PROCESSED = 102

  WHATSAPP_MESSAGE_MISSING_SENDER_PHONE_NUMBER = 110
  WHATSAPP_MESSAGE_SENDER_NOT_FOUND = 111
  
  # Whatsapp Scheduled Message (200-299)
  WHATSAPP_SCHEDULED_MESSAGE_SUCCESS = 200
  WHATSAPP_SCHEDULED_MESSAGE_FAILED = 201
  WHATSAPP_SCHEDULED_MESSAGE_PAST_DUE = 202
  WHATSAPP_SCHEDULED_MESSAGE_CANCELED = 203
  
  
  
class EventType(Enum):
  INVALID = 0
  WHATSAPP_MESSAGE = 10
  WHATSAPP_SCHEDULED_MESSAGE = 11
  